### ISSUE TITLE
'argument precision error' when running interpolation_and_fixed_times.livemd -- hexdocs guide out of date?

### ISSUE THREAD

**Issue by mrluc** [woodward/integrator#1]
Hi there -- I have an up-to-date local Livebook, which I frequently use for other code that requires eg. Nx and EXLA.

The first guide I tried to run from the 'Run in Livebook' button in hexdocs, [interpolation and fixed times](https://hexdocs.pm/integrator/interpolation_and_fixed_times.html), successfully installed dependencies but then died on the first cell:

First cell:
```elixir
alias Integrator.SampleEqns

t_initial = 0.0
t_final = 20.0
x_initial = Nx.tensor([2.0, 0.0])
solution = Integrator.integrate(&SampleEqns.van_der_pol_fn/2, [t_initial, t_final], x_initial)
```

Error:
```
** (Integrator.AdaptiveStepsize.ArgPrecisionError) argument precision error
    (integrator 0.1.2) lib/integrator/adaptive_stepsize.ex:835: anonymous fn/2 in Integrator.AdaptiveStepsize.check_nx_type/2
    (elixir 1.15.7) lib/enum.ex:984: Enum."-each/2-lists^foreach/1-0-"/2
    (integrator 0.1.2) lib/integrator/adaptive_stepsize.ex:831: Integrator.AdaptiveStepsize.check_nx_type/2
    (integrator 0.1.2) lib/integrator/adaptive_stepsize.ex:267: Integrator.AdaptiveStepsize.integrate/10
    /integrator.livemd#cell:fdzbnriq6d3bdjscdtpmiaylictcnm4m:6: (file)
```

And ... as I write this, I clicked around on Github, and I see that the last commit to that file made a change that fixes that for me!

**So I think maybe all that's needed is to re-publish the guides that are up on hexdocs**, as it looks like they're out of date.

For future searchers, it was a change like this:

```elixir
t_initial = Nx.tensor(0.0, type: :f64)
t_final = Nx.tensor(20.0, type: :f64)
x_initial = Nx.tensor([2.0, 0.0], type: :f64)
```

But best to use the [guides directory in github](https://github.com/woodward/integrator/tree/main/guides) as the same commit made a few changes across guides.

**Comment by woodward** [comment]
Hi, @mrluc 

First of all, I apologize for not getting around to this issue until now! So sorry; somehow I overlooked it. 

Yes, you're absolutely correct; the GitHub versions of the LiveBooks work ok, but the published docs were out-of-date (thank you for pointing that out), so I bumped the version number and republished the docs just now.

Just as an FYI, the API to `integrator` might still be a bit in flux as I figure out the best ways of using it.

Thank you for taking a look at `integrator`!

-- Greg
